const sideLinesMove = [
    {
        id: 1,
        title: "Thể Loại Phim",
        path: "/News",
        data: [
            {
                dataMovie_id: 1,
                picture: "https://www.galaxycine.vn/media/2019/4/10/640wx396h_1554864314405.jpg",
                title: "Avengers: Endgame",
                description: "Cú búng tay của Thanos đã khiến toàn bộ dân số biến mất một nửa. Các siêu anh hùng đánh mất bạn bè, người thân và đánh mất cả chính mình. Bộ sáu Avengers đầu tiên tứ tán. Iron Man kẹt lại ngoài không gian, Hawkeye mất tích. Thor, Captain America, Hulk và Black Widow đều chìm trong nỗi đau vô tận vì mất đi những người thân yêu. Họ phải làm gì để cứu vãn mọi chuyện ở ",
                quocGia: "Mỹ",
                theLoai: "Hành Động",
                namSanXuat: 2019,
                luotXem: 1500000,
                TinhTrang: "Sắp Chiếu",
            },
            {
                dataMovie_id: 2,
                picture: "https://www.galaxycine.vn/media/2020/9/3/avengers-infinity-war-4k-8k_1599105170451.jpg",
                title: "Avengers: Infinity War",
                description: "Biệt Đội Siêu Anh Hùng và đồng minh tiếp tục bảo vệ thế giới...",
                quocGia: "Mỹ",
                theLoai: "Khoa Học",
                namSanXuat: 2018,
                luotXem: 1300000,
                TinhTrang: "Sắp Chiếu",
            },
            {
                dataMovie_id: 3,
                picture: "https://www.galaxycine.vn/media/2019/1/14/1f53141dfb45271131393dd9635d6ed73c4fb4329ae9b786c0pimgpsh-fullsize-distr_1547463128661.jpg",
                title: "Cua Lại Vợ Bầu",
                description: "Một câu chuyện tình cảm hài hước...",
                quocGia: "Việt Nam",
                theLoai: "Hài, Tình Cảm",
                namSanXuat: 2019,
                luotXem: 400000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 4,
                picture: "https://www.galaxycine.vn/media/2020/9/5/75ee82f4d66dc6458306b811aff66370a269cd9d_1599240814983.jpg",
                title: "Aquaman",
                description: "Arthur Curry là kết tinh tình yêu của một người bình thường...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 900000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 5,
                picture: "https://www.galaxycine.vn/media/2019/3/20/lat-mat3_1553053164611.jpg",
                title: "Lật Mặt: Nhà Có Khách",
                description: "Dự án điện ảnh tiếp theo thuộc series phim Lật Mặt của đạo diễn Lý Hải là câu chuyện xoay quanh chuyến về thăm quê đầy trắc trở của Vy và những người bạn. Theo đó, tại nhà của Vy, nhóm bạn lần lượt gặp phải các tình huống vô cùng kỳ bí, lạ lùng. Đâu là lời giải đáp cho những bí ẩn đang rình rập quanh họ?",
                quocGia: "Thái Lan",
                theLoai: "Kinh Dị",
                namSanXuat: 2019,
                luotXem: 350000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 6,
                picture: "https://www.galaxycine.vn/media/2019/4/10/640wx396h_1554864314405.jpg",
                title: "Avengers: Endgame",
                description: "Cú búng tay của Thanos đã khiến toàn bộ dân số biến mất một nửa...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2019,
                luotXem: 1500000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 7,
                picture: "https://www.galaxycine.vn/media/2020/9/3/avengers-infinity-war-4k-8k_1599105170451.jpg",
                title: "Avengers: Infinity War",
                description: "Biệt Đội Siêu Anh Hùng và đồng minh tiếp tục bảo vệ thế giới...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 1300000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 8,
                picture: "https://www.galaxycine.vn/media/2019/1/14/1f53141dfb45271131393dd9635d6ed73c4fb4329ae9b786c0pimgpsh-fullsize-distr_1547463128661.jpg",
                title: "Cua Lại Vợ Bầu",
                description: "Một câu chuyện tình cảm hài hước...",
                quocGia: "Việt Nam",
                theLoai: "Hài, Tình Cảm",
                namSanXuat: 2019,
                luotXem: 400000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 9,
                picture: "https://www.galaxycine.vn/media/2020/9/5/75ee82f4d66dc6458306b811aff66370a269cd9d_1599240814983.jpg",
                title: "Aquaman",
                description: "Arthur Curry là kết tinh tình yêu của một người bình thường...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 900000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 10,
                picture: "https://www.galaxycine.vn/media/2019/3/20/lat-mat3_1553053164611.jpg",
                title: "Lật Mặt: Nhà Có Khách",
                description: "Chuyến thăm quê đầy trắc trở của Vy và nhóm bạn...",
                quocGia: "Việt Nam",
                theLoai: "Kinh Dị",
                namSanXuat: 2019,
                luotXem: 350000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 11,
                picture: "https://www.galaxycine.vn/media/2019/4/10/640wx396h_1554864314405.jpg",
                title: "Avengers: Endgame",
                description: "Cú búng tay của Thanos đã khiến toàn bộ dân số biến mất một nửa...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2019,
                luotXem: 1500000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 12,
                picture: "https://www.galaxycine.vn/media/2020/9/3/avengers-infinity-war-4k-8k_1599105170451.jpg",
                title: "Avengers: Infinity War",
                description: "Biệt Đội Siêu Anh Hùng và đồng minh tiếp tục bảo vệ thế giới...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 1300000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 13,
                picture: "https://www.galaxycine.vn/media/2019/1/14/1f53141dfb45271131393dd9635d6ed73c4fb4329ae9b786c0pimgpsh-fullsize-distr_1547463128661.jpg",
                title: "Cua Lại Vợ Bầu",
                description: "Một câu chuyện tình cảm hài hước...",
                quocGia: "Việt Nam",
                theLoai: "Hài, Tình Cảm",
                namSanXuat: 2019,
                luotXem: 400000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 14,
                picture: "https://www.galaxycine.vn/media/2020/9/5/75ee82f4d66dc6458306b811aff66370a269cd9d_1599240814983.jpg",
                title: "Aquaman",
                description: "Arthur Curry là kết tinh tình yêu của một người bình thường...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 900000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 15,
                picture: "https://www.galaxycine.vn/media/2019/3/20/lat-mat3_1553053164611.jpg",
                title: "Lật Mặt: Nhà Có Khách",
                description: "Chuyến thăm quê đầy trắc trở của Vy và nhóm bạn...",
                quocGia: "Việt Nam",
                theLoai: "Kinh Dị",
                namSanXuat: 2019,
                luotXem: 350000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 16,
                picture: "https://www.galaxycine.vn/media/2019/4/10/640wx396h_1554864314405.jpg",
                title: "Avengers: Endgame",
                description: "Cú búng tay của Thanos đã khiến toàn bộ dân số biến mất một nửa...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2019,
                luotXem: 1500000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 17,
                picture: "https://www.galaxycine.vn/media/2020/9/3/avengers-infinity-war-4k-8k_1599105170451.jpg",
                title: "Avengers: Infinity War",
                description: "Biệt Đội Siêu Anh Hùng và đồng minh tiếp tục bảo vệ thế giới...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 1300000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 18,
                picture: "https://www.galaxycine.vn/media/2019/1/14/1f53141dfb45271131393dd9635d6ed73c4fb4329ae9b786c0pimgpsh-fullsize-distr_1547463128661.jpg",
                title: "Cua Lại Vợ Bầu",
                description: "Một câu chuyện tình cảm hài hước...",
                quocGia: "Việt Nam",
                theLoai: "Hài, Tình Cảm",
                namSanXuat: 2019,
                luotXem: 400000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 19,
                picture: "https://www.galaxycine.vn/media/2020/9/5/75ee82f4d66dc6458306b811aff66370a269cd9d_1599240814983.jpg",
                title: "Aquaman",
                description: "Arthur Curry là kết tinh tình yêu của một người bình thường...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 900000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 20,
                picture: "https://www.galaxycine.vn/media/2019/3/20/lat-mat3_1553053164611.jpg",
                title: "Lật Mặt: Nhà Có Khách",
                description: "Chuyến thăm quê đầy trắc trở của Vy và nhóm bạn...",
                quocGia: "Việt Nam",
                theLoai: "Kinh Dị",
                namSanXuat: 2019,
                luotXem: 350000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 21,
                picture: "https://www.galaxycine.vn/media/2019/4/10/640wx396h_1554864314405.jpg",
                title: "Avengers: Endgame",
                description: "Cú búng tay của Thanos đã khiến toàn bộ dân số biến mất một nửa...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2019,
                luotXem: 1500000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 22,
                picture: "https://www.galaxycine.vn/media/2020/9/3/avengers-infinity-war-4k-8k_1599105170451.jpg",
                title: "Avengers: Infinity War",
                description: "Biệt Đội Siêu Anh Hùng và đồng minh tiếp tục bảo vệ thế giới...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 1300000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 23,
                picture: "https://www.galaxycine.vn/media/2019/1/14/1f53141dfb45271131393dd9635d6ed73c4fb4329ae9b786c0pimgpsh-fullsize-distr_1547463128661.jpg",
                title: "Cua Lại Vợ Bầu",
                description: "Một câu chuyện tình cảm hài hước...",
                quocGia: "Việt Nam",
                theLoai: "Hài, Tình Cảm",
                namSanXuat: 2019,
                luotXem: 400000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 24,
                picture: "https://www.galaxycine.vn/media/2020/9/5/75ee82f4d66dc6458306b811aff66370a269cd9d_1599240814983.jpg",
                title: "Aquaman",
                description: "Arthur Curry là kết tinh tình yêu của một người bình thường...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 900000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 25,
                picture: "https://www.galaxycine.vn/media/2019/3/20/lat-mat3_1553053164611.jpg",
                title: "Lật Mặt: Nhà Có Khách",
                description: "Chuyến thăm quê đầy trắc trở của Vy và nhóm bạn...",
                quocGia: "Việt Nam",
                theLoai: "Kinh Dị",
                namSanXuat: 2019,
                luotXem: 350000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 26,
                picture: "https://www.galaxycine.vn/media/2019/4/10/640wx396h_1554864314405.jpg",
                title: "Avengers: Endgame",
                description: "Cú búng tay của Thanos đã khiến toàn bộ dân số biến mất một nửa...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2019,
                luotXem: 1500000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 27,
                picture: "https://www.galaxycine.vn/media/2020/9/3/avengers-infinity-war-4k-8k_1599105170451.jpg",
                title: "Avengers: Infinity War",
                description: "Biệt Đội Siêu Anh Hùng và đồng minh tiếp tục bảo vệ thế giới...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 1300000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 28,
                picture: "https://www.galaxycine.vn/media/2019/1/14/1f53141dfb45271131393dd9635d6ed73c4fb4329ae9b786c0pimgpsh-fullsize-distr_1547463128661.jpg",
                title: "Cua Lại Vợ Bầu",
                description: "Một câu chuyện tình cảm hài hước...",
                quocGia: "Việt Nam",
                theLoai: "Hài, Tình Cảm",
                namSanXuat: 2019,
                luotXem: 400000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 29,
                picture: "https://www.galaxycine.vn/media/2020/9/5/75ee82f4d66dc6458306b811aff66370a269cd9d_1599240814983.jpg",
                title: "Aquaman",
                description: "Arthur Curry là kết tinh tình yêu của một người bình thường...",
                quocGia: "Mỹ",
                theLoai: " Viễn Tưởng",
                namSanXuat: 2018,
                luotXem: 900000,
                TinhTrang: "Đang Chiếu",
            },
            {
                dataMovie_id: 30,
                picture: "https://www.galaxycine.vn/media/2019/3/20/lat-mat3_1553053164611.jpg",
                title: "Lật Mặt: Nhà Có Khách",
                description: "Chuyến thăm quê đầy trắc trở của Vy và nhóm bạn...",
                quocGia: "Việt Nam",
                theLoai: "Kinh Dị",
                namSanXuat: 2019,
                luotXem: 350000,
                TinhTrang: "Đang Chiếu",
            },

        ]
    },
    {
        id: 2,
        title: "Diễn Viên",
        path: "/News",
        data: [
            {
                id_StarMovie: 1,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 2,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 3,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 4,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 5,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 6,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 7,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 8,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 9,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 10,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 11,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 12,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 13,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 14,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },
            {
                id_StarMovie: 15,
                picture: "https://cdn.galaxycine.vn/media/c/h/chris-ngang_1.jpg",
                title: "Chris Evans",
                description: "Khác với Chris Hemsworth vẫn đang loay hoay trong hình tượng vị thần sấm sét..."
            },

        ]
    },
    {
        id: 3,
        title: "Đạo Diễn",
        path: "/News"
    },
    {
        id: 4,
        title: "Bình Luận Phim",
        path: "/News"
    },
    {
        id: 5,
        title: "Blog Điện ảnh",
        path: "/News"
    }
];

export default sideLinesMove;
